### ISSUE TITLE
Утечка памяти.

### ISSUE THREAD

**Issue by Leymooo** [Shevchik/CreativeLimiter#2]
Привет. При запуске севрера плагин съедает 13 гб оперативной памяти. И сервер запускается очень долго. Без плагина все норм.
Количество пользователей: 7.5к
Количество блоков: 3.5 млн.

Плагин очень полезный. Очень долго не могли понять почему так много озу тратиться.  Я на рб скинул тебе видно. Правда я забыл там показать htop. Но я надеюсь что ты мне поверишь, что утечка в этом плагине.

**Comment by Shevchik** [comment]
Почисть данные блоков установленных креативами, а также данные инвенатрей.
